### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by epicfaace** [thinhvo0108/react-paypal-express-checkout#16] opened 2017-12-24 16:32 UTC
That would be useful so it can be used with typescript.

**Comment by thinhvo0108** [comment] 2018-03-12 05:56
Your suggestion of using typescript is very welcomed!
Could you please create some PRs if possible, but please make your solution buildable and runnable (as in the end, just 1 file "dist/index.js" will be used to update on NPM)
Thanks!

**Comment by thinhvo0108** [comment] 2018-04-06 03:29
Close this issue, which was a suggestion, not a bug!
We may add typescript later, anyway, thanks!

**Closed by thinhvo0108** 2018-04-06 03:29 UTC
